### ISSUE TITLE
Create Design

### ISSUE THREAD

**Issue by amrouda50** [parimsuka/hackaTUM-check24#4]
edit here all the design ideas discussed as checkboxs

- [x] First iteration of the desing
- [x] Second iteration of review by @amrouda50 
- [ ] Final review

**Comment by havenousername** [comment]
Guys design is here https://www.figma.com/file/gs8L9bxnF61lbJkuWyCRgZ/Untitled?type=design&node-id=6%3A13&mode=dev

I am closing for now, we can reiterate later
